get_random_str_from_list: Selects one random string from list, outputs the selected string

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -1,6 +1,12 @@
 #!/usr/bin/env bash
 set -eu -o pipefail
 
+die() {
+    local exitcode=$1
+    echo 2>&1 ERROR: "$@"
+    exit $exitcode
+}
+
 basedir=$(cd "$(dirname "$0")" && pwd -P)
 
 cd "$basedir"
@@ -9,7 +15,8 @@ pytest -q "$@"
 
 out="$basedir/.build/tftd.out"
 
+
 python tftd.py > "$out" || die 1 'FAILED: bad exit'
-grep -q 'A broad mind lacks focus' "$out" 2>&1 || die 1 'FAILED: bad output'
+[[ $(wc -l <$out) -ge 1 ]] || die 1 'FAILED: bad output'
 
 echo OK
